# Server
server.port=8081

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/auth_db

# JWT
jwt.secret=xXKVhlE4ief91CfBmZHJ/+/vFufnavaKNd1SdwYnlo4=
jwt.expiration=86400000

# Actuator
management.endpoints.web.exposure.include=health

spring.data.mongodb.auto-index-creation=false
