# Server
server.port=8082

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/order-service
spring.data.mongodb.auto-index-creation=false

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# JWT — mesmo secret do auth-service
jwt.secret=xXKVhlE4ief91CfBmZHJ/+/vFufnavaKNd1SdwYnlo4=

# Actuator
management.endpoints.web.exposure.include=health